### PR TITLE
feat(reporter): custom reporter can be loaded by its package name

### PR DESCRIPTION
**Pull request by doshprompt**
```js
var htmlhint = require('gulp-htmlhint');

gulp.src('./src/*.html')
    .pipe(htmlhint())
    .pipe(htmlhint.reporter('htmlhint-stylish'))
```

### CODE REVIEW

**Comment by bezoerb** [comment]
Nice :)
Could you provide a testcase for this?

**Comment by doshprompt** [comment]
@bezoerb let me do it now, hang on. I also need to make some tests for my shiny new reporter :)

**Comment by bezoerb** [comment]
:+1:

**Comment by bezoerb** [comment]
Awesome, thanks for working on this.

**Comment by doshprompt** [comment]
@bezoerb np, could you please make a new release tag for this and publish it to npm? Thanks!

**Comment by bezoerb** [comment]
@doshprompt https://github.com/bezoerb/gulp-htmlhint/releases/tag/v0.3.0

**Comment by doshprompt** [comment]
thanks!

**Pull request merged**
